
FROM node:15.14.0-alpine3.13 AS build-stage
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
#Ideally, should run as a non root user!
FROM nginx:1.20.0-alpine
COPY --from=build-stage /mysite/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
